---
- name: "remove default NGINX config file"
  when: nginx_remove_default_server_confs
  command: rm /etc/nginx/conf.d/default.conf
           removes=/etc/nginx/conf.d/default.conf
  notify: reload nginx

- name: "remove example_ssl NGINX config file"
  when: nginx_remove_default_server_confs
  command: rm /etc/nginx/conf.d/example_ssl.conf
           removes=/etc/nginx/conf.d/example_ssl.conf
  notify: reload nginx

- name: "set NGINX config file"
  when: nginx_replace_default_http_conf
  copy: src=nginx.conf
        dest=/etc/nginx/nginx.conf
  notify: reload nginx
