---
- include: install.deb.yml
  when: ansible_os_family == "Debian"

- include: configure.yml

- name: "ensure NGINX is started"
  service: name=nginx state=started enabled=yes
  changed_when: False
